# Generated by Django 4.2.20 on 2025-05-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_utilisateur_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
