# Generated by Django 4.2.20 on 2025-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_utilisateur_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_utilisateur',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
