# Generated by Django 4.2.20 on 2025-05-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_utilisateur_is_2fa_verified_utilisateur_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
