# Generated by Django 4.2.20 on 2025-05-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_utilisateur_is_2fa_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='old_cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
