# Generated by Django 4.2.20 on 2025-05-02 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_billet', models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('famille', 'Famille')], max_length=20)),
                ('date_disponible', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/offres/')),
            ],
        ),
    ]
