# Generated by Django 4.2.20 on 2025-05-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offre_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/offres/'),
        ),
    ]
