# Generated by Django 4.2.20 on 2025-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offre_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
