# Generated by Django 4.2.20 on 2025-05-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_transaction_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='code_transaction',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
