# Generated by Django 4.2.20 on 2025-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_transaction_code_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='type_billet',
            field=models.CharField(choices=[('solo', 'Solo'), ('duo', 'Duo'), ('famille', 'Famille')], default='solo', max_length=20),
        ),
    ]
